- name: Ensure proxy_params exists
  copy:
    dest: /etc/nginx/proxy_params
    content: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

- name: Configure Nginx
  copy:
    dest: /etc/nginx/conf.d/{{ app_name }}.conf
    content: |
      server {
          listen 80;
          server_name {{ domain_name }};

          location = /favicon.ico { access_log off; log_not_found off; }
          location /static/ {
              root {{ project_dir }};
          }

          location / {
              include proxy_params;
              proxy_pass http://unix:{{ gunicorn_socket }};
          }
      }
  notify: Reload Nginx

- name: Remove default Nginx config (if exists)
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Restart Nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
